### ISSUE TITLE
Duplicate module name: react-animated 

### ISSUE THREAD

**Issue by mopilo** [Flutterwave/rave-react-native#1]
After installing react-native-rave, i got this error

Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-animated
  Paths: /Users/mopah/Documents/ReactNativeApps/mobile/node_modules/react-native-rave/node_modules/react-native/Libraries/Animated/release/package.json collides with /Users/mopah/Documents/ReactNativeApps/mobile/node_modules/react-native/Libraries/Animated/release/package.json

**Comment by MaestroJolly** [comment]
Hi @mopilo, please you can refer to this link https://medium.com/@jeanjacquesbagui/react-native-providesmodule-naming-collision-error-6bc090925fb3 to assist you in resolving the issue

**Comment by mopilo** [comment]
I was able to solve it, i just upgraded the package.
