### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: jest-haste-map: @providesModule naming collision:   Duplicate module name: react-native

### ISSUE THREAD

**Issue by i-mighty** [Flutterwave/rave-react-native#10]
I have reviewed the issue by mopilo #1  and i saw  the response. However, all the soluttions in that article didn't work for me.
I want to be sure, is it a version problem?
What should be the correct version number in my package.json?
How do I really fix this problem?

**Comment by i-mighty** [comment]
Update!!!!
I was able to get it to work with react native 0.55.2 and gradle 2.14.1 and I got a nice looking interface.
However, I would like to use a latter version of react native (precisely the latest version `0.57.7`).
How would I go about it?
Would an update of the plug-in be necessary?
Please I would really appreciate your help.

**Comment by r1z11** [comment]
I found a solution here
https://github.com/facebook/metro/issues/265#issuecomment-446636417
create a rn-cli.config.js file in the root of your project and paste the code there

**Comment by i-mighty** [comment]
Thanks.
I would try it and get back to you.

**Comment by ochui** [comment]
> Update!!!!
> I was able to get it to work with react native 0.55.2 and gradle 2.14.1 and I got a nice looking interface.
> However, I would like to use a latter version of react native (precisely the latest version `0.57.7`).
> How would I go about it?
> Would an update of the plug-in be necessary?
> Please I would really appreciate your help.

it works like charm. Thanks

**Comment by ochui** [comment]
i fix it in this fork https://github.com/ochui/rave-react-native

**Comment by raheemazeezabiodun** [comment]
I solved this by adding in `rn-cli.config.js`
```
const blacklist = require('metro-config/src/defaults/blacklist');

module.exports = {
    resolver: {
        blacklistRE: blacklist([
            /node_modules\/.*\/node_modules\/react-native\/.*/,
        ])
    },
};```

**Comment by MaestroJolly** [comment]
The fix for this error is to go into the node modules of your application, locate the react native folder in the rave react native sdk and then delete it.

**Comment by hardikmobileappsdev** [comment]
### _**hhgjg**_

**Comment by hardikmobileappsdev** [comment]
![Uploading Screen Shot 2019-03-12 at 2.54.21 PM.png…]()

**Comment by pinchezkinja** [comment]
I fixed this issue by deleting both react and react-native folders from react-native-rave/node-modules folder.

**Comment by temiadesina** [comment]
Closing this issue now, because there is a documented resolution path.
