### ISSUE TITLE
MPesa Error

### ISSUE THREAD

**Issue by pinchezkinja** [Flutterwave/rave-react-native#15]
After installing this library, am trying to make mpesa payments but it keeps responding with 'KES transaction only is allowed. Anyone with a solution to this?
![screenshot_20190221-102416](https://user-images.githubusercontent.com/43640820/53151053-33796780-35c3-11e9-819d-1ee04ca78998.png)

**Comment by MaestroJolly** [comment]
Hi @pinchezkinja , did you pass KES as the currency and KE as the country?

**Comment by pinchezkinja** [comment]
Hi too @MaestroJolly. Yes I have. When I change paymenttype and page to card, transactions are successful with KES values. But mpesa doesnt work.

**Comment by anjolabassey** [comment]
hi @pinchezkinja can you confirm if you are getting this on live or test environment

**Comment by pinchezkinja** [comment]
Hello..I tweaked some code and it's now working.  After initiating a
charge,the res.data.status value is always this: "successful,waiting
customer validation".

 So I removed the 'data' part it read like:

if(resp.status.toUpperCase=== "SUCCESS" && resp.data.currency==="KES") ...
-> that is in components-Mpesa-index.js line 73. Now it's fine.

**Comment by anjolabassey** [comment]
Hi @pinchezkinja good to hear it's working. a fix to this will also reflect in the SDK and will be updated asap.

**Comment by pinchezkinja** [comment]
@anjolabassey Thanks for your response.
