### ISSUE TITLE
iOS 13 doesn't support WebView

### ISSUE THREAD

**Issue by benjamin-daniel** [Flutterwave/rave-react-native#38]
After inputing the card details, it show as:

<img width="292" alt="Screenshot 2019-10-02 at 2 58 13 PM" src="https://user-images.githubusercontent.com/19100745/66050960-02ccb980-e526-11e9-90d7-908a3d2e4711.png">

**Comment by anjolabassey** [comment]
hello @benjamin-daniel apologies for the delay. This issue has been resolved, kindly test and confirm.

**Comment by temiadesina** [comment]
PR #41 closes this issue.
