### ISSUE TITLE
Recurring Payment

### ISSUE THREAD

**Issue by vrinch** [Flutterwave/rave-react-native#56]
great job here guys. however, I would like to know If its possible to achieve recurring payments, and if yes, how do you advice one to go about it.

**Comment by Corvus97** [comment]
Hello @vrinch ,

Apologies for the late reply.

Kindly be advised that this SDK is no longer supported by the Team. Please use the new SDK (https://github.com/Flutterwave/flutterwave-react-native) for a better experience.

Also, you can join our discussion on our forum(https://developer.flutterwave.com/discuss) for more tips on issue resolution.

Best regards,
Cornelius
