### ISSUE TITLE
Custom User Interface of Rave-React-Native

### ISSUE THREAD

**Issue by MalcolmTomisin** [Flutterwave/rave-react-native#59]
## Expose an Interface to customize UI of rave-react-native

Using the rave component without being able to customize the theme/UI of the rave component comes up inconsistent when using it in apps with a consistent theme/UI, sometimes making it look foreign to the app flow. Perhaps expose some props that can be passed into the component for customization of the UI?

**Comment by getaplotdev** [comment]
This is a very valid issue.

**Comment by Corvus97** [comment]
Hello @MalcolmTomisin  ,

Apologies for the late reply.

Kindly be advised that this SDK is no longer supported by the Team. Please use the new SDK (https://github.com/Flutterwave/flutterwave-react-native) for a better experience.

Also, you can join our discussion on our forum(https://developer.flutterwave.com/discuss) for more tips on issue resolution.

Best regards,
Cornelius
