### ISSUE TITLE
FlutterWave - ListView - 0.61 not working

### ISSUE THREAD

**Issue by yasikrehman** [Flutterwave/rave-react-native#68]
Listview is deprecated from React Native 0.60

## Describe the Bug

 Hi Team, 
 I am using react-native-rave with react-native version 0.61,
 My Issue is React-native was removed Listview Option from 0.60 .

How to Fix it.

## System Information

 - Operating system: Linux
 - Rave version: ^2.2.5
 - React-Native: 0.61.5

**Comment by MalcolmTomisin** [comment]
I had this issue when I upgraded expo to the recent sdk 36.

**Comment by yasikrehman** [comment]
> I had this issue when I upgraded expo to the recent sdk 36.

Did you find the solution for it ?

**Comment by abdulsamadola** [comment]
I'm facing the same issues, did you find any work around ?

**Comment by MalcolmTomisin** [comment]
I reverted to SDK 35

**Comment by devmuhammad** [comment]
SOLUTION: I had this same issue after updating to SDK37.
Resolved this by changing the dependency in node_modules>react-native-rave>package.json "react-native-keyboard-aware-scroll-view" version to 0.8.0

 Then in your cli, cd to node_modules>react-native-rave - npm install

That should fix the issue

> I'm facing the same issues, did you find any work around ?



> I reverted to SDK 35
> […](#)



> > I had this issue when I upgraded expo to the recent sdk 36.
> 
> Did you find the solution for it ?

**Comment by abdulsamadola** [comment]
I solved the issue by removing the **node_modules**  inside react-native-rave entirely;  _node_modules>react-native-rave>node_modules_

**Comment by Corvus97** [comment]
Hello @yasikrehman , @MalcolmTomisin and @abdulsamadola 

Apologies for the late reply.

Kindly be advised that this SDK is no longer supported by the Team. Please use the new SDK (https://github.com/Flutterwave/flutterwave-react-native) for a better experience.

Also, you can join our discussion on our forum(https://developer.flutterwave.com/discuss) for more tips on issue resolution.

Best regards,
Cornelius
