### ISSUE TITLE
FLW_ERR

### ISSUE THREAD

**Issue by emma255** [Flutterwave/rave-react-native#69]
When i do card payment i got the  the following

- **status:** error

- **message:** Unfortunately, we could not charge you because we are having issues connecting to     your provider

- **vbvrespcode:** RR

- **vbvrespmessage:** INVALID_REQUEST: Relationship not found for merchantID 3057FL18, card type MC

- **data.code:** FLW_ERR

- **data.message:** Unfortunately, we could not charge you because we are having issues connecting to your provider

- **data.chargeResponseMessage:** INVALID_REQUEST: Relationship not found for merchantID 3057FL18, card type MC

- **data.chargeResponseCode:** RR

## System Information

 - Operating system: Ubuntu 19.10
 - Rave version: 2.2.5

Help please... Thanks

**Comment by Corvus97** [comment]
Hi @emma255,

Thanks for reaching out to the Team.

Kindly share your merchant ID via email to hi@flutterwavego.com

Kind regards,
Cornelius.
