### ISSUE TITLE
Invariant Violation: Element ref was specified as String

### ISSUE THREAD

**Issue by justmykk** [Flutterwave/rave-react-native#7]
When I tried to use the react native sdk, I go this error. **Invariant Violation: Element ref was specified as a string (1) but no owner was set. **.

react-native: 0.55.4

**Comment by MaestroJolly** [comment]
Hello @justmykk , you can try updating your react native and react to see if it fixes the issue.

**Comment by raheemazeezabiodun** [comment]
I tried this with react-native version `0.57.1`, I got the same error. 
How do I fix this? thanks

**Comment by MaestroJolly** [comment]
The fix for this error is to go into the node modules of your application, locate the react native folder in the rave react native sdk and then delete it, you can refer this link: https://github.com/MaestroJolly/rave-react-native

**Comment by klazbaba** [comment]
Deleting only the react-native folder did not work for me.
I was able to get it running by also deleting the react folder.

**Comment by MaestroJolly** [comment]
great @klazbaba .

**Comment by temiadesina** [comment]
Closing this issue, because there is a documented resolution for it above.
