### ISSUE TITLE
Invariant Violation: webView has been removed from react native. 

### ISSUE THREAD

**Issue by OlaAde** [Flutterwave/rave-react-native#71]
I got this error after I tap on Pay with Debit Card. 
![Screenshot_20200320-190335_patient_react_app](https://user-images.githubusercontent.com/16616844/77193467-9434e580-6ade-11ea-9a53-3af0a457ee32.jpg)

These are my details. 
"native-base": "^2.13.12",
    "react": "16.9.0",
    "react-native": "0.61.5"

**Comment by harrybanda** [comment]
Same issue here did you fix the problem?

**Comment by OlaAde** [comment]
No. Had to use their native ios and native android sdks. There is a way to use native code in a RN application. Although the ios sdk is also buggy.

**Comment by Corvus97** [comment]
Hello @OlaAde and @harrybanda  ,

Apologies for the late reply.

Kindly be advised that this SDK is no longer supported by the Team. Please use the new SDK (https://github.com/Flutterwave/flutterwave-react-native) for a better experience.

Also, you can join our discussion on our forum(https://developer.flutterwave.com/discuss) for more tips on issue resolution.

Best regards,
Cornelius
