### ISSUE TITLE
ListView has been removed from React Native

### ISSUE THREAD

**Issue by emaitee** [Flutterwave/rave-react-native#73]
I get an error 
```
ListView has been removed from React Native
```
when trying to use react-native-rave's Rave component

## System Information

 - Operating system: windows 10
 - Rave version:  2.2.5

## Additional Context
React Native version: 0.60.5

**Comment by Corvus97** [comment]
Hello @emaitee  ,

Apologies for the late reply.

Kindly be advised that this SDK is no longer supported by the Team. Please use the new SDK (https://github.com/Flutterwave/flutterwave-react-native) for a better experience.

Also, you can join our discussion on our forum(https://developer.flutterwave.com/discuss) for more tips on issue resolution.

Best regards,
Cornelius
