### ISSUE TITLE
Using react native webview 

### ISSUE THREAD

**Issue by johneyo** [Flutterwave/rave-react-native#74]
i get the url show up on the screen after entering my otp

## Describe the Bug
i enter my otp and the url shows up on my screen, i think it has to do with my react native package being above the one used on this module.

i opted in for react-native-webview instead of the webview exported from the core react native

## System Information

 - Operating system: Mac Os running on ios simulator
 - Rave version:2.2.5

## Additional Context

"https://coreflutterwaveprod.com/flwmvva/ptds3pg?resp=%7B%22batchno%22:%2220200418%22,%22authorizeId%22:%22068621%22,%22merchtransactionreference%22:%22PT-FLW233956462%22,%22orderinfo%22:%22PT-FLW233956462%22,%22receiptno%22:%22010822241279%22,%22redirecturl%22:%22%22,%22responsehtml%22:%22%22,%22responsecode%22:%2200%22,%22responsemessage%22:%22APPROVED%22,%22transactionreference%22:%22PT-FLW233956462%22,%22externalreference%22:%22PT-FLW233956462%22,%22amount%22:%221.00%22,%22currency%22:%22NGN%22%7D"

That is what shows up

**Comment by Corvus97** [comment]
Hello @johneyo  ,

Apologies for the late reply.

Kindly be advised that this SDK is no longer supported by the Team. Please use the new SDK (https://github.com/Flutterwave/flutterwave-react-native) for a better experience.

Also, you can join our discussion on our forum(https://developer.flutterwave.com/discuss) for more tips on issue resolution.

Best regards,
Cornelius
