### ISSUE TITLE
Bank Payment doesn't work for Zenith and Access bank

### ISSUE THREAD

**Issue by EzenwakaKaycee** [Flutterwave/rave-react-native#76]
Bank payment not working for some banks e.g. Zenith and Access bank

## Describe the Bug

I observed that rave react naive plugin is having issues with bank payment and particularly paying with zenith banks crashes the app.

## System Information

 - Operating system: React native/ Android
 - Rave version:2.2.5

**Comment by Corvus97** [comment]
Hello @EzenwakaKaycee  ,

Apologies for the late reply.

Kindly be advised that this SDK is no longer supported by the Team. Please use the new SDK (https://github.com/Flutterwave/flutterwave-react-native) for a better experience.

Also, you can join our discussion on our forum(https://developer.flutterwave.com/discuss) for more tips on issue resolution.

Best regards,
Cornelius
